"""Add last_checked to strategies

Revision ID: 0308d4b57407
Revises: 3b5f05319b21
Create Date: 2025-05-19 21:52:41.145402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0308d4b57407'
down_revision: Union[str, None] = '3b5f05319b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('last_checked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'last_checked')
    # ### end Alembic commands ###
