"""Initial migration

Revision ID: 0b1c5bed34b7
Revises: 6d9bf5a0fa93
Create Date: 2025-03-13 09:40:41.822689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1c5bed34b7'
down_revision: Union[str, None] = '6d9bf5a0fa93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
