"""Add broker table

Revision ID: 18ac5dc2cd27
Revises: b06fbcb50149
Create Date: 2025-05-22 16:43:11.970173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ac5dc2cd27'
down_revision: Union[str, None] = 'b06fbcb50149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alpaca_api_secret')
    op.drop_column('users', 'alpaca_api_key')
    op.drop_column('users', 'alpaca_base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alpaca_base_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('alpaca_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('alpaca_api_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
