"""Trade_log and signal_log tables modified

Revision ID: 3b5f05319b21
Revises: 792b8cbaf9da
Create Date: 2025-05-19 14:06:11.126973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5f05319b21'
down_revision: Union[str, None] = '792b8cbaf9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_logs', sa.Column('executed', sa.Boolean(), nullable=True))
    op.add_column('signal_logs', sa.Column('result', sa.String(), nullable=True))
    op.add_column('trade_logs', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('trade_logs', sa.Column('exit_time', sa.DateTime(), nullable=True))
    op.add_column('trade_logs', sa.Column('pnl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_logs', 'pnl')
    op.drop_column('trade_logs', 'exit_time')
    op.drop_column('trade_logs', 'exit_price')
    op.drop_column('signal_logs', 'result')
    op.drop_column('signal_logs', 'executed')
    # ### end Alembic commands ###
