"""Add API settings

Revision ID: 57c78c42fbc7
Revises: f98bbe7afdef
Create Date: 2025-03-27 08:23:29.061639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c78c42fbc7'
down_revision: Union[str, None] = 'f98bbe7afdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alpaca_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('alpaca_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('alpaca_base_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alpaca_base_url')
    op.drop_column('users', 'alpaca_api_secret')
    op.drop_column('users', 'alpaca_api_key')
    # ### end Alembic commands ###
