"""finalize SignalLog and strategy-ticker schema

Revision ID: 6430d9e97586
Revises: 7b1b6cbf869a
Create Date: 2025-05-15 12:30:45.752792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6430d9e97586'
down_revision: Union[str, None] = '7b1b6cbf869a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
