"""Refactor strategies table

Revision ID: 6c69722786c6
Revises: f0aec5b42eef
Create Date: 2025-05-24 10:46:16.764378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c69722786c6'
down_revision: Union[str, None] = 'f0aec5b42eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('use_notional', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('use_balance_percent', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('strategies', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('strategies', sa.Column('sl_tp_is_percent', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('default_timeframe', sa.String(), nullable=True))
    op.alter_column('strategies', 'trade_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('strategies', 'market_check_frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('strategies', 'automation_mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('strategies', 'notify_on_signal')
    op.drop_column('strategies', 'auto_trade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('auto_trade', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('notify_on_signal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('strategies', 'automation_mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('strategies', 'market_check_frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('strategies', 'trade_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('strategies', 'default_timeframe')
    op.drop_column('strategies', 'sl_tp_is_percent')
    op.drop_column('strategies', 'take_profit')
    op.drop_column('strategies', 'stop_loss')
    op.drop_column('strategies', 'use_balance_percent')
    op.drop_column('strategies', 'use_notional')
    # ### end Alembic commands ###
