"""Add password field to User

Revision ID: 6d9bf5a0fa93
Revises: ad7d5b48b07c
Create Date: 2025-03-13 09:38:44.723065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9bf5a0fa93'
down_revision: Union[str, None] = 'ad7d5b48b07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
