"""add strategy type for ML

Revision ID: 76aedce6cc57
Revises: e6253fbae397
Create Date: 2025-05-26 11:55:00.516202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76aedce6cc57'
down_revision: Union[str, None] = 'e6253fbae397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('strategy_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'strategy_type')
    # ### end Alembic commands ###
