"""Add strategy advanced settings

Revision ID: 792b8cbaf9da
Revises: 57f4fe48b8f3
Create Date: 2025-05-17 19:57:21.006861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792b8cbaf9da'
down_revision: Union[str, None] = '57f4fe48b8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('signal_logic', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('confirmation_candles', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('notify_on_signal', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('auto_trade', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('trade_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'trade_amount')
    op.drop_column('strategies', 'order_type')
    op.drop_column('strategies', 'auto_trade')
    op.drop_column('strategies', 'notify_on_signal')
    op.drop_column('strategies', 'confirmation_candles')
    op.drop_column('strategies', 'signal_logic')
    # ### end Alembic commands ###
