"""finalize SignalLog and strategy-ticker schema

Revision ID: 7b1b6cbf869a
Revises: ec55435a2696
Create Date: 2025-05-15 12:15:04.851247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1b6cbf869a'
down_revision: Union[str, None] = 'ec55435a2696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
