"""Add user_preferences table

Revision ID: 8d5d8b30e9ee
Revises: b1bd0d515a4b
Create Date: 2025-05-23 10:53:47.125760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5d8b30e9ee'
down_revision: Union[str, None] = 'b1bd0d515a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('default_timeframe', sa.String(), nullable=True),
    sa.Column('auto_trading_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_trade_amount', sa.Float(), nullable=True),
    sa.Column('use_percentage', sa.Boolean(), nullable=True),
    sa.Column('default_stop_loss', sa.Float(), nullable=True),
    sa.Column('default_take_profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
