"""Add TensorFlow strategy fields

Revision ID: a8ced0872857
Revises: 76aedce6cc57
Create Date: 2025-05-28 12:12:02.750740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ced0872857'
down_revision: Union[str, None] = '76aedce6cc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('training_ticker', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('training_from_date', sa.Date(), nullable=True))
    op.add_column('strategies', sa.Column('training_to_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'training_to_date')
    op.drop_column('strategies', 'training_from_date')
    op.drop_column('strategies', 'training_ticker')
    # ### end Alembic commands ###
