"""Edit backtest table

Revision ID: b06fbcb50149
Revises: ba69e42ac7d5
Create Date: 2025-05-22 09:05:00.134404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06fbcb50149'
down_revision: Union[str, None] = 'ba69e42ac7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('equity_curve', sa.JSON(), nullable=True))
    op.add_column('backtest_results', sa.Column('trades', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_results', 'trades')
    op.drop_column('backtest_results', 'equity_curve')
    # ### end Alembic commands ###
