"""Add TensorFlow date fields

Revision ID: b32d89e00d6c
Revises: a8ced0872857
Create Date: 2025-05-28 14:41:19.063129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32d89e00d6c'
down_revision: Union[str, None] = 'a8ced0872857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('last_trained_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'last_trained_at')
    # ### end Alembic commands ###
