"""Edit trade_log table

Revision ID: ba69e42ac7d5
Revises: 0308d4b57407
Create Date: 2025-05-20 21:28:13.625533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba69e42ac7d5'
down_revision: Union[str, None] = '0308d4b57407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_logs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('trade_logs', sa.Column('is_order', sa.Boolean(), nullable=True))
    op.add_column('trade_logs', sa.Column('broker_order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_logs', 'broker_order_id')
    op.drop_column('trade_logs', 'is_order')
    op.drop_column('trade_logs', 'status')
    # ### end Alembic commands ###
