"""finalize SignalLog and strategy-ticker schema

Revision ID: ec55435a2696
Revises: 87df029fd076
Create Date: 2025-05-14 21:38:53.229419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec55435a2696'
down_revision: Union[str, None] = '87df029fd076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('user_stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_stock_id'], ['user_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_tickers_id'), 'strategy_tickers', ['id'], unique=False)
    op.add_column('signal_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('signal_logs', sa.Column('action', sa.String(), nullable=False))
    op.add_column('signal_logs', sa.Column('debug_data', sa.JSON(), nullable=True))
    op.drop_constraint('signal_logs_strategy_id_fkey', 'signal_logs', type_='foreignkey')
    op.create_foreign_key(None, 'signal_logs', 'strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'signal_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('signal_logs', 'signal')
    op.create_unique_constraint(None, 'user_stocks', ['user_id', 'ticker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stocks', type_='unique')
    op.add_column('signal_logs', sa.Column('signal', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'signal_logs', type_='foreignkey')
    op.drop_constraint(None, 'signal_logs', type_='foreignkey')
    op.create_foreign_key('signal_logs_strategy_id_fkey', 'signal_logs', 'strategies', ['strategy_id'], ['id'])
    op.drop_column('signal_logs', 'debug_data')
    op.drop_column('signal_logs', 'action')
    op.drop_column('signal_logs', 'user_id')
    op.drop_index(op.f('ix_strategy_tickers_id'), table_name='strategy_tickers')
    op.drop_table('strategy_tickers')
    # ### end Alembic commands ###
