"""Add notification fields to the user_preferences table

Revision ID: f0aec5b42eef
Revises: 8d5d8b30e9ee
Create Date: 2025-05-23 11:30:03.348257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0aec5b42eef'
down_revision: Union[str, None] = '8d5d8b30e9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('email_alerts_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('notify_on_signal', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('notify_on_order_filled', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('notify_on_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'notify_on_error')
    op.drop_column('user_preferences', 'notify_on_order_filled')
    op.drop_column('user_preferences', 'notify_on_signal')
    op.drop_column('user_preferences', 'email_alerts_enabled')
    # ### end Alembic commands ###
